----------DAY-9----------

In [1]:
#Import libraries
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pandas as pd
import warnings 
warnings.filterwarnings("ignore")

# Download NLTK resources (run once)
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to C:\Users\User
[nltk_data]     2\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\User
[nltk_data]     2\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\User
[nltk_data]     2\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

PROGRAM-1

In [2]:
#  Preprocess a paragraph: lowercase, remove punctuation, remove stopwords 
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk

# Input paragraph
text = """Machine Learning is one of the most popular fields in Computer Science.
It helps computers learn from data and make predictions.  """

# Convert to lowercase
text = text.lower()

# Remove punctuation
text = text.translate(str.maketrans('', '', string.punctuation))

# Tokenize words
words = word_tokenize(text)

# Remove stopwords
stop_words = set(stopwords.words('english'))
filtered_words = [word for word in words if word not in stop_words]

# Join words back into text
processed_text = " ".join(filtered_words)

print("Original Text : ")
print(text)

print("\nProcessed Text : ")
print(processed_text)

Original Text : 
machine learning is one of the most popular fields in computer science
it helps computers learn from data and make predictions  

Processed Text : 
machine learning one popular fields computer science helps computers learn data make predictions


PROGRAM-2

In [3]:
# Convert text corpus to TF-IDF matrix using TfidfVectorizer 
from sklearn.feature_extraction.text import TfidfVectorizer

# text corpus
corpus = [
    "Machine learning is amazing",
    "Machine learning is used in data science",
    "Data science and artificial intelligence",
    "Artificial intelligence uses machine learning"
]

# Create TF-IDF vectorizer
vectorizer = TfidfVectorizer()

# Convert text to TF-IDF matrix
tfidf_matrix = vectorizer.fit_transform(corpus)

# Convert to DataFrame
df = pd.DataFrame(tfidf_matrix.toarray() , columns=vectorizer.get_feature_names_out())

print(df)

    amazing       and  artificial      data       in  intelligence        is  \
0  0.640655  0.000000    0.000000  0.000000  0.00000      0.000000  0.505100   
1  0.000000  0.000000    0.000000  0.364459  0.46227      0.000000  0.364459   
2  0.000000  0.535566    0.422247  0.422247  0.00000      0.422247  0.000000   
3  0.000000  0.000000    0.450852  0.000000  0.00000      0.450852  0.000000   

   learning   machine   science     used      uses  
0  0.408922  0.408922  0.000000  0.00000  0.000000  
1  0.295061  0.295061  0.364459  0.46227  0.000000  
2  0.000000  0.000000  0.422247  0.00000  0.000000  
3  0.365003  0.365003  0.000000  0.00000  0.571848  


PROGRAM-3 and 4

In [4]:
# Train Naive Bayes on SMS spam dataset 
# Import libraries
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import random

# Ham messages
ham_messages = [
    "Are you coming to class today?",
    "Please call me when you arrive.",
    "Let's meet at the library.",
    "See you tomorrow.",
    "Have a nice day.",
    "Can you send me the notes?",
    "The meeting starts at 10 AM.",
    "Please submit the assignment.",
    "Let's study together tonight.",
    "Don't forget the exam tomorrow."
]

# Spam messages
spam_messages = [
    "Congratulations! You won a free mobile.",
    "Claim your cash prize now.",
    "You have won a lottery worth $1000.",
    "Limited time offer. Click now.",
    "Free entry into the contest.",
    "Win a free vacation package.",
    "Urgent! Your account has won a prize.",
    "Exclusive offer just for you.",
    "Get a free gift card now.",
    "Earn money quickly from home."
]

data = {"label": [] , "message": []}

# Generate 30 random records
for i in range(30):
    label = random.choice(["ham", "spam"])
    if label == "ham":
        message = random.choice(ham_messages)
    else:
        message = random.choice(spam_messages)
    data["label"].append(label)
    data["message"].append(message)

# Create DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv("sms_spam.csv", index=False)
print("sms_spam.csv created successfully!")

# Load dataset
df = pd.read_csv("sms_spam.csv", encoding='latin-1')

# Convert labels to numbers
df['label'] = df['label'].map({'ham': 0 , 'spam': 1})

# Features and target
X = df['message']
y = df['label']

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X , y , test_size=0.2 , random_state=42)

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(stop_words='english')
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Train Naive Bayes model
model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

# Predictions
y_pred = model.predict(X_test_tfidf)

# Evaluation
print("Accuracy : ", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix : ")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report : ")
print(classification_report(y_test, y_pred))

#Predict a New Message
new_message = ["Congratulations! You have won a free gift."]
print(new_message)
new_tfidf = vectorizer.transform(new_message)
prediction = model.predict(new_tfidf)
if prediction[0] == 1:
    print("Spam")
else:
    print("Ham")

sms_spam.csv created successfully!
Accuracy :  0.8333333333333334

Confusion Matrix : 
[[1 0]
 [1 4]]

Classification Report : 
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.80      0.89         5

    accuracy                           0.83         6
   macro avg       0.75      0.90      0.78         6
weighted avg       0.92      0.83      0.85         6

['Congratulations! You have won a free gift.']
Spam


----------PRACTICE SHEET------------

PROGRAM-5

In [5]:
# Movie review sentiment classifier: positive vs negative 
# Import libraries
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create sample movie review dataset
data = {
    "review": [
        "This movie was fantastic and amazing",        
        "I loved the acting and story",
        "An excellent film with great performances",
        "The movie was wonderful and inspiring",
        "Absolutely loved this movie",      
        "It was a brilliant experience",
        "The film was terrible and boring",
        "I hated this movie",
        "Worst movie ever made",
        "The acting was very poor",
        "Completely disappointing film",
        "The story was dull and boring",
        "Amazing cinematography and great music",
        "The plot was interesting and engaging",
        "Outstanding direction and acting",
        "Bad screenplay and weak acting",
        "Not worth watching",
        "The movie was a waste of time",
        "Excellent storyline and characters",
        "Horrible movie experience",
        "I enjoyed every moment",
        "Fantastic performances by the actors",
        "Very disappointing ending",
        "The film was enjoyable",
        "Poor direction and bad script",
        "Loved the soundtrack and visuals",
        "Terrible acting and boring plot",
        "One of the best movies",
        "Awful and disappointing film",
        "A masterpiece of cinema"
    ],

    "sentiment": [
        "positive", "positive", "positive", "positive", "positive",
        "positive", "negative", "negative", "negative", "negative",
        "negative", "negative", "positive", "positive", "positive",
        "negative", "negative", "negative", "positive", "negative",
        "positive", "positive", "negative", "positive", "negative",
        "positive", "negative", "positive", "negative", "positive"
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv('Movie_review.csv', index=False)
print("CSV file created successfully!")

# Load dataset
df = pd.read_csv("Movie_review.csv")

# Convert labels to numbers
df["sentiment"] = df["sentiment"].map({"negative": 0 , "positive": 1})

# Features and target
X = df["review"]
y = df["sentiment"]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X , y , test_size=0.2 , random_state=42)

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(stop_words="english")
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Train Naive Bayes model
model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

# Predictions
y_pred = model.predict(X_test_tfidf)

# Evaluation
print("Accuracy : ", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix : ")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report : ")
print(classification_report(y_test, y_pred))

#Predict a New Review
new_review = ["The movie was absolutely amazing and enjoyable"]
print(new_review)
new_tfidf = vectorizer.transform(new_review)
prediction = model.predict(new_tfidf)
if prediction[0] == 1:
    print("Positive Review")
else:
    print("Negative Review")

CSV file created successfully!
Accuracy :  0.16666666666666666

Confusion Matrix : 
[[0 4]
 [1 1]]

Classification Report : 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.20      0.50      0.29         2

    accuracy                           0.17         6
   macro avg       0.10      0.25      0.14         6
weighted avg       0.07      0.17      0.10         6

['The movie was absolutely amazing and enjoyable']
Positive Review


PROGRAM-6

In [6]:
# News category classifier using TF-IDF + Logistic Regression 
# Import libraries
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create news dataset
data = {
    "news": [
        "The team won the cricket match",
        "The player scored a century",
        "Football championship starts next week",
        "The coach announced the squad",
        "Government passed a new law",
        "The election results were announced",
        "Parliament discussed the budget",
        "The minister gave a speech",
        "New smartphone launched today",
        "Artificial intelligence is growing rapidly",
        "The company released a new software update",
        "Scientists developed a new robot",
        "The movie was released worldwide",
        "The actor won an award",
        "The music concert was successful",
        "The director announced a new film",
        "Tennis tournament begins tomorrow",
        "The president addressed the nation",
        "New laptop models were introduced",
        "The singer released a new album",
        "Basketball team won the championship",
        "Political parties started campaigning",
        "Researchers developed an AI system",
        "The film received positive reviews",
        "Cricket players attended training camp",
        "The government introduced a policy",
        "Technology companies invest in AI",
        "The actress starred in a new movie",
        "Olympic games begin next month",
        "The parliament approved the bill"
    ],

    "category": [
        "Sports", "Sports", "Sports", "Sports",
        "Politics", "Politics", "Politics", "Politics",
        "Technology", "Technology", "Technology", "Technology",
        "Entertainment", "Entertainment", "Entertainment", "Entertainment",
        "Sports", "Politics", "Technology", "Entertainment",
        "Sports", "Politics", "Technology", "Entertainment",
        "Sports", "Politics", "Technology", "Entertainment",
        "Sports", "Politics"
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv('News.csv', index=False)
print("CSV file created successfully!")

# Load dataset
df = pd.read_csv("News.csv")

# Features and target
X = df["news"]
y = df["category"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X , y , test_size=0.2 , random_state=42 , stratify=y)

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(stop_words='english')
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Logistic Regression model
model = LogisticRegression(max_iter=1000)

# Train model
model.fit(X_train_tfidf, y_train)

# Predictions
y_pred = model.predict(X_test_tfidf)

# Evaluation
print("Accuracy : ", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix : ")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report : ")
print(classification_report(y_test, y_pred))

# Predict a New News Article
new_news = ["The cricket team won the final match"]
new_tfidf = vectorizer.transform(new_news)
prediction = model.predict(new_tfidf)
print(new_news)
print("Predicted Category:", prediction[0])

CSV file created successfully!
Accuracy :  0.5

Confusion Matrix : 
[[1 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 0 0]]

Classification Report : 
               precision    recall  f1-score   support

Entertainment       1.00      1.00      1.00         1
     Politics       0.33      0.50      0.40         2
       Sports       0.50      0.50      0.50         2
   Technology       0.00      0.00      0.00         1

     accuracy                           0.50         6
    macro avg       0.46      0.50      0.47         6
 weighted avg       0.44      0.50      0.47         6

['The cricket team won the final match']
Predicted Category: Sports
